global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'dapr'
    scrape_interval: 5s

    static_configs:
      - targets: ['host.docker.internal:9090']  # This allows Docker container to access host
